-- File generated by the BNF Converter (bnfc 2.9.4).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Parser.

module Parser.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Parser.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Parser.Abs.TokUnit where
  prt _ (Parser.Abs.TokUnit (_,i)) = doc $ showString i
instance Print Parser.Abs.UIdent where
  prt _ (Parser.Abs.UIdent (_,i)) = doc $ showString i
instance Print Parser.Abs.PIdent where
  prt _ (Parser.Abs.PIdent (_,i)) = doc $ showString i
instance Print Parser.Abs.PInteger where
  prt _ (Parser.Abs.PInteger (_,i)) = doc $ showString i
instance Print Parser.Abs.SCPL where
  prt i = \case
    Parser.Abs.SCPLPROG defns -> prPrec i 0 (concatD [prt 0 defns])

instance Print [Parser.Abs.Defn] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print Parser.Abs.Defn where
  prt i = \case
    Parser.Abs.DEFN pident stmt -> prPrec i 0 (concatD [prt 0 pident, doc (showString "="), prt 1 stmt])

instance Print Parser.Abs.Stmt where
  prt i = \case
    Parser.Abs.CASESTMT exp caseterms -> prPrec i 2 (concatD [doc (showString "case"), prt 0 exp, doc (showString "of"), doc (showString "{"), prt 0 caseterms, doc (showString "}")])
    Parser.Abs.IFSTMT exp stmt1 stmt2 -> prPrec i 2 (concatD [doc (showString "if"), prt 0 exp, doc (showString "then"), prt 2 stmt1, doc (showString "else"), prt 2 stmt2])
    Parser.Abs.BARESTMT exp -> prPrec i 2 (concatD [prt 0 exp])
    Parser.Abs.ELet let_ letinstmt stmt -> prPrec i 1 (concatD [prt 0 let_, prt 0 letinstmt, doc (showString "in"), prt 1 stmt])

instance Print Parser.Abs.Let where
  prt i = \case
    Parser.Abs.LET -> prPrec i 0 (concatD [doc (showString "let")])
    Parser.Abs.LRec -> prPrec i 0 (concatD [doc (showString "letrec")])

instance Print Parser.Abs.CaseTerm where
  prt i = \case
    Parser.Abs.CASE_STMT casepattern stmt -> prPrec i 0 (concatD [prt 0 casepattern, doc (showString "->"), prt 1 stmt])

instance Print Parser.Abs.LetInStmt where
  prt i = \case
    Parser.Abs.LET_IN_STMT pident exp -> prPrec i 0 (concatD [prt 0 pident, doc (showString "="), prt 0 exp])

instance Print Parser.Abs.Type where
  prt i = \case
    Parser.Abs.TYPEARROW typen type_ -> prPrec i 0 (concatD [prt 0 typen, doc (showString "->"), prt 0 type_])
    Parser.Abs.TYPENext typen -> prPrec i 0 (concatD [prt 0 typen])

instance Print Parser.Abs.TypeN where
  prt i = \case
    Parser.Abs.TYPEUNIT tokunit -> prPrec i 0 (concatD [prt 0 tokunit])
    Parser.Abs.TYPECONST_VAR uident -> prPrec i 0 (concatD [prt 0 uident])
    Parser.Abs.TYPELIST type_ -> prPrec i 0 (concatD [doc (showString "["), prt 0 type_, doc (showString "]")])
    Parser.Abs.TYPEPROD types -> prPrec i 0 (concatD [doc (showString "<"), prt 0 types, doc (showString ">")])
    Parser.Abs.TYPEBRACKET type_ -> prPrec i 0 (concatD [doc (showString "("), prt 0 type_, doc (showString ")")])
    Parser.Abs.CONST_TYPE constanttype -> prPrec i 0 (concatD [prt 0 constanttype])

instance Print [Parser.Abs.TypeN] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [Parser.Abs.Type] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [Parser.Abs.UIdent] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Parser.Abs.CasePattern where
  prt i = \case
    Parser.Abs.TRUE_PATTERN -> prPrec i 0 (concatD [doc (showString "True")])
    Parser.Abs.FALSE_PATTERN -> prPrec i 0 (concatD [doc (showString "False")])

instance Print [Parser.Abs.CaseTerm] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print Parser.Abs.Exp where
  prt i = \case
    Parser.Abs.EInt pinteger -> prPrec i 15 (concatD [prt 0 pinteger])
    Parser.Abs.ETrue -> prPrec i 15 (concatD [doc (showString "True")])
    Parser.Abs.EFalse -> prPrec i 15 (concatD [doc (showString "False")])
    Parser.Abs.EVar pident -> prPrec i 15 (concatD [prt 0 pident])
    Parser.Abs.EString str -> prPrec i 15 (concatD [printString str])
    Parser.Abs.EList exps -> prPrec i 15 (concatD [doc (showString "["), prt 0 exps, doc (showString "]")])
    Parser.Abs.ECall pident exps -> prPrec i 15 (concatD [prt 0 pident, doc (showString "("), prt 0 exps, doc (showString ")")])
    Parser.Abs.ENeg exp -> prPrec i 13 (concatD [doc (showString "-"), prt 14 exp])
    Parser.Abs.CONSTERM exp1 exp2 -> prPrec i 13 (concatD [prt 13 exp1, doc (showString ":"), prt 14 exp2])
    Parser.Abs.EAPPEND exp1 exp2 -> prPrec i 12 (concatD [prt 12 exp1, doc (showString "++"), prt 13 exp2])
    Parser.Abs.EMul exp1 exp2 -> prPrec i 12 (concatD [prt 12 exp1, doc (showString "*"), prt 13 exp2])
    Parser.Abs.EDiv exp1 exp2 -> prPrec i 12 (concatD [prt 12 exp1, doc (showString "/"), prt 13 exp2])
    Parser.Abs.EAdd exp1 exp2 -> prPrec i 11 (concatD [prt 11 exp1, doc (showString "+"), prt 12 exp2])
    Parser.Abs.ESub exp1 exp2 -> prPrec i 11 (concatD [prt 11 exp1, doc (showString "-"), prt 12 exp2])
    Parser.Abs.ELt exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString "<"), prt 10 exp2])
    Parser.Abs.EGt exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString ">"), prt 10 exp2])
    Parser.Abs.ELEq exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString "<="), prt 10 exp2])
    Parser.Abs.EGEq exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString ">="), prt 10 exp2])
    Parser.Abs.EEq exp1 exp2 -> prPrec i 8 (concatD [prt 8 exp1, doc (showString "=="), prt 9 exp2])
    Parser.Abs.ENEq exp1 exp2 -> prPrec i 8 (concatD [prt 8 exp1, doc (showString "!="), prt 9 exp2])
    Parser.Abs.EAnd exp1 exp2 -> prPrec i 4 (concatD [prt 4 exp1, doc (showString "&&"), prt 5 exp2])
    Parser.Abs.EOr exp1 exp2 -> prPrec i 3 (concatD [prt 3 exp1, doc (showString "||"), prt 4 exp2])
    Parser.Abs.ELambda pidents stmt -> prPrec i 1 (concatD [doc (showString "\\"), prt 0 pidents, doc (showString "->"), prt 1 stmt])

instance Print [Parser.Abs.PIdent] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x, doc (showString " ")]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString " "), prt 0 xs]

instance Print Parser.Abs.TypeAnnotation where
  prt i = \case
    Parser.Abs.TYPEANNOTATION type_ -> prPrec i 0 (concatD [doc (showString "::"), prt 0 type_])
    Parser.Abs.TYPEANNOTATION_EMPTY -> prPrec i 0 (concatD [])

instance Print [Parser.Abs.Exp] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Parser.Abs.ConstantType where
  prt i = \case
    Parser.Abs.INTEGER pinteger -> prPrec i 0 (concatD [prt 0 pinteger])
    Parser.Abs.STRING str -> prPrec i 0 (concatD [printString str])
    Parser.Abs.CHAR c -> prPrec i 0 (concatD [prt 0 c])
    Parser.Abs.DOUBLE d -> prPrec i 0 (concatD [prt 0 d])
